config/routes.rb
Rails.application.routes.draw do

  root to: 'spotify#home'

  get '/auth/spotify/callback', to: 'spotify#show'

  get '/logout', to: 'spotify#logout', as: 'logout_users'

  get 'spotify/compare', to: 'spotify#compare'

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
# class HomeController < ApplicationController
# 	include SpotifyHelper

# 	def index
# 	end

# 	def home

# 	end

# 	#not in use
# 	def show
# 		user_search = params["artist"]["artist"].downcase.gsub(" ","+")
# 		@artist_search = JSON.load(open("https://api.spotify.com/v1/search?q=#{user_search}&type=artist"))
# 		@artist_id = @artist_search["artists"]["items"][0]["id"]
# 		@artist_info = JSON.load(open("https://api.spotify.com/v1/artists/#{@artist_id}/related-artists"))
# 		@name = []

# 		@artist_info["artists"].each do |y|
			
# 			@name << y["name"]
# 		end

# 	end


# end

app/controllers/spotify_controller.rb
class SpotifyController < ApplicationController
    include RelatedHelper
    include SpotifyHelper

    def home 
    end

    def show
      # spotify_user = RSpotify::User.new(request.env['omniauth.auth'])
      session[:spotify] = request.env['omniauth.auth']
      users_artists
      related_art

      # session[:output], session[:artists_all_info], session[:rel_artist_rec], session[:user_artist_related] = @output, @artists_all_info, @rel_artist_rec, @user_artist_related

      render :action => 'compare'

    end

    def compare
    end

    def logout
      session.delete(:spotify)
      redirect_to root_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/related_helper.rb
module RelatedHelper
  	include SpotifyCallsHelper

    def users_artists
      # receive user's info from spotify
      @user = user_call
      @artists_all_info = {} #{name =[id, uri]}   // all artists
      @artists = {}
      # @artists = {artist id => artist name}  // artists from user's saved tracks
  		i = 0 
  		k = 40 
      # api limited, use counters to offset and repeat call
      u_saved = saved_tracks(k,i)
  		until u_saved == [] do 
  			u_saved.each do |art|
				  name = art.artists[0].name
          # add to all_artists_info hash
          @artists_all_info[name] = [art.artists[0].id, art.artists[0].uri]
          # if artist not in artists hash
					@artists[art.artists[0].id] ||= name
        end
        i += 40 
        u_saved = saved_tracks(k,i)
      end
	   end


  	def related_art
  		@user_artist_related = Hash.new{|h,k| h[k] = [] }   # users artists to arr of 20 recommended {"Tame Impala"=>["Grizzly Bear",Kurt Vile"]} 
  		@rel_artist_rec = Hash.new{|h,k| h[k] = [] }     # recommended artists to arr of user's artist they were recommended from 
      @rel_art_count = Hash.new(0)

      # iterating through user's artist ids, api for related artists
      @artists.keys.each do |a_id|
        @rel_art_info = related_a(a_id)  # call to spot_calls_helper for array of 20 artists
        @rel_art_info.each do |related|
          # if not an artist in user's saved track list  				
          builder(related, a_id)
        end
      end
      # output for view, most frequent counted similar artists
      @output = @rel_art_count.sort_by { |k,v| v }.reverse[0..29].to_h
    end

    def builder(related, id_art)
      if !@artists.keys.include?(related.id)
        # add to all_artists_info hash
        @artists_all_info[related.name] ||= [related.id, related.uri] 
        @user_artist_related[@artists[id_art]] << related.name
        @rel_artist_rec[related.name] << @artists[id_art]     # adding user's artist to hash of recommended
        @rel_art_count[related.name] += 1          
      end
    end      

    # playlists

    # def user_playlists
    #   @u_playlists = {}
    #   @all_songs_count = @rel_art_count

    #   p_lists = play_lists
    #   p_lists.each do |play|
    #     p_list_tracks = play_tracks(play)
    #     p_list_tracks.each do |song|

    #     end
    #   end
    # end

    # def play_builder(song)
    #   @u_playlists[song.artists[0].id] ||= song.artists[0].name
    # end



    # get user's top artists, generates a hash for highcharts
    def top_artists
      @top_artists_hash = {}
      fav_artists = favor
      fav_artists.each do |f|
        @top_artists_hash[f.name] = {}
        @user_artist_related.each do |f_rel_art|
          @top_artists_hash[f.name][f_rel_art] = {}
          @rel_artist_rec[f_rel_art].each do |user_also_rec|
            if f.name != user_also_rec
              @top_artists_hash[f.name][f_rel_art][user_also_rec] = "1"
            end
          end
          if @top_artists_hash[f.name][f_rel_art] == {}
            @top_artists_hash[f.name][f_rel_art]["none"] = "0"
          end
        end
      end
      @top = @top_artists_hash.to_json
    end
    # json opbject for highcharts
    #   @top_artists_hash =  { 
    #     "sufjan" =  {
    #        rec1 =  {
    #           "otherUserArtist1" = 1,
    #           otherUserArtist2 = 1
    #         },
    #         rec2 = {
    #           otherUserArtist3 = 1,
    #           otherUserArtist4 = 1
    #         }
    #     }
    #   }


end

app/helpers/spotify_calls_helper.rb
module SpotifyCallsHelper
	def user_call 
		RSpotify::User.new(session[:spotify])
	end

	def saved_tracks(k,i)
		@user.saved_tracks(limit:k,offset:i)
	end

	def related_a(id)
		artist = RSpotify::Artist.find(id)
		artist.related_artists
	end

	def favor 
		@user.top_artists[0..19]
	end

	def play_lists
		@user.playlists
	end
	# playlists tracks
	def play_tracks(play) 
		play.tracks
	end

end

app/helpers/spotify_helper.rb
module SpotifyHelper
	def current_user
		if session[:spotify]
			@current_user ||= RSpotify::User.new(session[:spotify])
		end
	end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SpotifyArtistRecommendation</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/spotify/_login_out.html.erb
	<% if current_user %>
		<div id="logout"><%=link_to "Logout", logout_users_path, id:'logout' %></div>
	<% else %>
		<div id="spotify-link">
			<a href='/auth/spotify'> <button class="btn btn-lg btn-success" id="login">Log in with Spotify</button></a>
	<% end %>		

app/views/spotify/_music_player.html.erb
<iframe src="https://embed.spotify.com/?uri=<%="#{rel_uri}"%>" width="300" height="80" frameborder="0" allowtransparency="true"></iframe>

app/views/spotify/_related_artists.html.erb
<% binding.pry %>
<% if current_user %>	
	<div id="list-container">
	  <ul id="exp-list">
	  	<h2 style="display:inline-block"> Artists most related to those in your library: </h2>
	    <% @output.each do |rel, num|  %>
	    	<% rel_uri = @artists_all_info[rel][1]  %>
	    <li> <h2 style="display:inline-block"> <%= "#{rel}, #{num}  "%> </h2> 
	    
	    <% r = rel.gsub(" ","")  %> 
	    <h3 id="<%="#{r}"%>" class="listen-to" style="display:inline-block"> Listen </h3>

		<script type="text/javascript">
			$( "#<%="#{r}"%>" ).click(function() {
  				$( "#f-<%="#{r}"%>" ).toggle( "slow", function() {
  				});
			});
			$( "#a<%="#{r}"%>" ).click(function() {
  				$( "#f<%="#{r}"%>" ).toggle( "slow", function() {
  				});
			});
		</script>

	    <div style="display:none;" style="display:inline-block;" id="f-<%="#{r}"%>">
	    	<!--  -->
	    </div>
	      <ul>
	      <h3> Related to these artists in your library: </h3>
	      	<% @rel_artist_rec[rel].each do |user_a|  %>
	        <li> <%= user_a %>
	          <ul>
	          <h3> All artists related to <%=user_a%>: </h3>
	          <% @user_artist_related[user_a].each do |rec_a|  %>
	            <li>  <%= rec_a  %> 

	            </li>
	          <% end  %>
	          </ul>
	        </li>
	        <% end %> 
	      </ul>
	    </li>
	    <%end%>
	  </ul>
	</div>
<% end %>	

app/views/spotify/compare.html.erb
	<div id="list-container">
	  <ul id="exp-list">
	  	<h2 style="display:inline-block"> Artists most related to those in your library: </h2>
	    <% @output.each do |rel, num|  %>
	    	<% rel_uri = @artists_all_info[rel][1]  %>
	    <li> <h2 style="display:inline-block"> <%= "#{rel}, #{num}  "%> </h2> 
	    
	    <% r = rel.gsub(" ","")  %> 
	    <h3 id="<%="#{r}"%>" class="listen-to" style="display:inline-block"> Listen </h3>

		<script type="text/javascript">
			$( "#<%="#{r}"%>" ).click(function() {
  				$( "#f-<%="#{r}"%>" ).toggle( "slow", function() {
  				});
			});
			// $( "#a<%="#{r}"%>" ).click(function() {
  	// 			$( "#f<%="#{r}"%>" ).toggle( "slow", function() {
  	// 			});
			// });
			// $('#<%="#{r}"%>').click(function(){
   // 				$('#-<%="#{r}"%>').attr('src', 'https://embed.spotify.com/?uri=<%="#{rel_uri}"%>');
			// });
		</script>

	    <div style="display:none;" style="display:inline-block;" id="f-<%="#{r}"%>">
<iframe src="https://embed.spotify.com/?uri=<%="#{rel_uri}"%>" width="300" height="80" frameborder="0" allowtransparency="true"></iframe>


	    </div>
	      <ul>
	      <h3> Related to these artists in your library: </h3>
	      	<% @rel_artist_rec[rel].each do |user_a|  %>
	        <li> <%= user_a %>
	          <ul>
	          <h3> All artists related to <%=user_a%>: </h3>
	          <% @user_artist_related[user_a].each do |rec_a|  %>
	            <li>  <%= rec_a  %> 

	            </li>
	          <% end  %>
	          </ul>
	        </li>
	        <% end %> 
	      </ul>
	    </li>
	    <%end%>
	  </ul>
	</div>

app/views/spotify/home.html.erb
<div class="home-page" id="gradient"> 
	<div id= "home-title">
		<h1 id="title"> Spotify Artist Recommendations </h1>
	</div>
</div>

<div class="login-out"> <%= render partial: "login_out", locals: {current: @current_user} %></div>



<p class="footer" id="footer-about"> About </p>
<p class="footer" id="footer-text"> Analyzes a user's saved tracks and shows connections between recommended artists. <br>Created by <a href="https://github.com/skoltz">Steve Koltz</a></p>
     

app/views/spotify/show.html.erb
<% binding.pry %>
<% if current_user %>	
	<div id="list-container">
	  <ul id="exp-list">
	  	<h2 style="display:inline-block"> Artists most related to those in your library: </h2>
	    <% @output.each do |rel, num|  %>
	    	<% rel_uri = @artists_all_info[rel][1]  %>
	    <li> <h2 style="display:inline-block"> <%= "#{rel}, #{num}  "%> </h2> 
	    
	    <% r = rel.gsub(" ","")  %> 
	    <h3 id="<%="#{r}"%>" class="listen-to" style="display:inline-block"> Listen </h3>

		<script type="text/javascript">
			$( "#<%="#{r}"%>" ).click(function() {
  				$( "#f-<%="#{r}"%>" ).toggle( "slow", function() {
  				});
			});
			$( "#a<%="#{r}"%>" ).click(function() {
  				$( "#f<%="#{r}"%>" ).toggle( "slow", function() {
  				});
			});
		</script>

	    <div style="display:none;" style="display:inline-block;" id="f-<%="#{r}"%>">
	    	<!--  -->
	    </div>
	      <ul>
	      <h3> Related to these artists in your library: </h3>
	      	<% @rel_artist_rec[rel].each do |user_a|  %>
	        <li> <%= user_a %>
	          <ul>
	          <h3> All artists related to <%=user_a%>: </h3>
	          <% @user_artist_related[user_a].each do |rec_a|  %>
	            <li>  <%= rec_a  %> 

	            </li>
	          <% end  %>
	          </ul>
	        </li>
	        <% end %> 
	      </ul>
	    </li>
	    <%end%>
	  </ul>
	</div>
<% end %>	

app/views/spotify/spotify.html.erb
<!DOCTYPE html>
<html>
<head>
<title> Spotify Artist Recommendations </title>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script> 
</head>
<body>
	<div id="list-container">
	  <ul id="exp-list">
	  	<h2 style="display:inline-block"> Artists most related to those in your library: </h2>
	    <% @output.each do |rel, num|  %>
	    	<% rel_uri = @artists_all_info[rel][1]  %>
	    
	    <li> <h2 style="display:inline-block"> <%= "#{rel}, #{num}  "%> </h2> 
	    
	    <% r = rel.gsub(" ","")  %> 
	    <h3 id="<%="#{r}"%>" class="listen-to" style="display:inline-block"> Listen </h3>

		<script type="text/javascript">
			$( "#<%="#{r}"%>" ).click(function() {
  				$( "#f-<%="#{r}"%>" ).toggle( "slow", function() {
  				});
			});
			$( "#a<%="#{r}"%>" ).click(function() {
  				$( "#f<%="#{r}"%>" ).toggle( "slow", function() {
  				});
			});
		</script>

	    <div style="display:none;" style="display:inline-block;" id="f-<%="#{r}"%>">
	    	<!--  -->
	    </div>


	      <ul>
	      <h3> Related to these artists in your library: </h3>
	      	<% @rel_artist_rec[rel].each do |user_a|  %>
	        <li> <%= user_a %>
	          <ul>
	          <h3> All artists related to <%=user_a%>: </h3>
	          <% @user_artist_related[user_a].each do |rec_a|  %>
	            <li>  <%= rec_a  %> 

	            </li>
	          <% end  %>
	          </ul>
	        </li>
	        <% end %> 
	      </ul>
	    </li>
	    <%end%>
	  </ul>
	</div>


</body>
</html>







<style>
	html, body {
		font-family: "Proxima Nova","Helvetica Neue",Helvetica,Arial,sans-serif;
  		padding: 0;
  		margin: 0;
	}

	#list-container{
	  margin-top:15px;
	}
	 
	#exp-list ul, li {
	    list-style: none;
	    margin:0;
	    padding:0;
	    cursor: pointer;
	}
	#exp-list ul {
		padding-left: 6%;
	}
	#exp-list p {
	    margin:0;
	    display:block;
	}
	#exp-list p:hover {
	    background-color:#121212;
	}
	#exp-list li {
	    line-height:160%;
	    text-indent:0px;
	    background-position: 1px 8px;
	    padding-left: 20px;
	    background-repeat: no-repeat;
	}
	 
	/* collapsed state for list element */
/*	#exp-list .collapsed {
	    background-image: url('/assets/collapsed.png');
	}
	#exp-list .expanded {
	    background-image: url('/assets/expanded.png');
	}*/

	#exp-list .collapsed {
	    background-image: url('http://www.i2symbol.com/images/symbols/subscript/subscript_plus_sign_u208A_icon_256x256.png');
	    background-size: 20px;
	}
	#exp-list .expanded {
	    background-image: url('http://www.i2symbol.com/images/symbols/math/minus_sign_u2212_icon_256x256.png');
	    background-size: 15px;
	}


	.circles {
		background-color: black;
		font-color: white;
		/*#BBF3CF*/
		width: 100px;
		height: 100px;
		-moz-border-radius: 50px;
		-webkit-border-radius: 50px;
		border-radius: 50px;
	}

	.listen-to {
		display: inline-block;
		padding: 7px;
		-moz-border-radius: 100px / 50px;
		-webkit-border-radius: 100px / 50px;
		border-radius: 100px / 50px;
	}

	.listen-to:hover { 
    background-color: #1ED760;
    color: white;
	}

</style>


<script type="text/javascript">

	$(function prepareList() {
		$('#exp-list').find('li:has(ul)').unbind('click').click(function(event) {
			if(this == event.target) {
				$(this).toggleClass('expanded');
				$(this).children('ul').toggle('medium');
			}
			return false;
		}).addClass('collapsed').removeClass('expanded').children('ul').hide();
	 
		//Hack to add links inside the cv
		$('#exp-list a').unbind('click').click(function() {
			window.open($(this).attr('href'));
			return false;
		});
		//Create the button functionality
		$('#expand-list').unbind('click').click(function() {
			$('.collapsed').addClass('expanded');
			$('.collapsed').children().show('medium');
		})
		$('#collapse-list').unbind('click').click(function() {
			$('.collapsed').removeClass('expanded');
			$('.collapsed').children().hide('medium');
		})
	});

</script>

app/views/users/music_player.html.erb
<iframe src="https://embed.spotify.com/?uri=<%="#{rel_uri}"%>" width="300" height="80" frameborder="0" allowtransparency="true"></iframe>